// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrdtqtpawxvsqufevgct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyZHRxdHBhd3h2c3F1ZmV2Z2N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDA4NjAsImV4cCI6MjA2ODE3Njg2MH0.S_eSotnTu9t20Je9TxqDBOX1xm_Zya0xOQdc1gwHDPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});